name: Build

on:
  schedule:
    - cron: "1 */18 * * *"
  push:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Setup 
        uses: actions/setup-node@v3.6.0
      - name: Build
        uses: xgugugu/build-aur-action@master
        with:
          repo-name: "nana quickjspp-git koodo-reader-bin kooha sdl2pp videomass dwarfs-bin qbittorrent-enhanced-qt5 python-conda-package-handling python-conda authenticator qqmusic-electron vcpkg qqmusic-bin cpr xclicker quickjs vala-language-server hmcl-bin python-gtts dialect icalingua++ bilibili-bin cpeditor visual-studio-code-bin netease-cloud-music-gtk4 watt-toolkit-bin github-desktop-bin wemeet-bin google-chrome microsoft-edge-stable-bin linuxqq"
      - name: Upload
        uses: ncipollo/release-action@v1.12.0
        with: 
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.pkg.tar.zst,./xgugugu.db,./xgugugu.db.tar.gz"
          token: ${{ secrets.ACCESS_TOKEN }}
