name: AUR

on:
    schedule:
      - cron: "1 */8 * * *"
    push:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize
        uses: actions/setup-node@v3.6.0
      - name: Build
        uses: ./build-aur-action
        with:
          repos: "python-yapsy linuxqq authenticator xclicker python-gtts dialect icalingua++ cpeditor visual-studio-code-bin netease-cloud-music-gtk4 watt-toolkit-bin github-desktop-bin wemeet-bin google-chrome microsoft-edge-stable-bin bun-bin text-engine extension-manager zig-dev-bin uvw listen1 ttf-ms-fonts dwarfs-bin bindtointerface apostrophe graphs escambo postman-bin python-daltonlens python-python-crontab python-python-lorem python-textstat python-uuid6 devtoolbox"
      - name: Upload
        uses: ncipollo/release-action@v1.12.0
        with: 
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./dist/*.*"
          token: ${{ secrets.ACCESS_TOKEN }}
