name: Build

on:
  schedule:
    - cron: "1 */8 * * *"
  push:

jobs:
  build:
    strategy:
      matrix:
        repos: [icalingua++]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-node@v3.6.0
      - name: Build
        uses: DuckSoft/build-aur-action@v1.1
        with:
          repo-name: ${{ matrix.repos }}
      - name: Update
        run: |
          repo-add ./*/xgugugu.db.tar.gz *.tar.zst
      - name: Upload
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.tar.zst"
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Final
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/xgugugu.db.tar.gz"
          token: ${{ secrets.ACCESS_TOKEN }}
