name: Build

on:
  schedule:
    - cron: "1 */8 * * *"
  push:

jobs:
  build:
    strategy:
      matrix:
        repos: [icalingua++, bilibili-bin, cpeditor, visual-studio-code-bin, python-gtts, dialect, netease-cloud-music-gtk4]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-node@v3.6.0
      - name: Build 
        uses: xgugugu/build-aur-action@master
        with:
          repo-name: ${{ matrix.repos }}
      - name: Upload
        uses: ncipollo/release-action@v1.12.0
        with: 
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.tar.zst,./xgugugu.db,./xgugugu.db.tar.gz"
          token: ${{ secrets.ACCESS_TOKEN }}
